name: Build-2019
env:
  PINGGY_TOKEN: ${{ secrets.PINGGY_TOKEN }}
  EMAIL: ${{ secrets.EMAIL }}
on: workflow_dispatch

jobs:
  runner-2019:
    runs-on: windows-2019
    steps:
    - name: Git check
      run: |
        choco install wget
        git --version
    - name: Checkout (Thirdparty)
      run: |
        git clone https://gitlab.com/${{ secrets.GITLAB_REPOSITORY }}.git work
        cd work
        git switch ${{ secrets.GITLAB_REF }}
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: amd64
    - name: Download extra software
      run: |
        wget https://download.sysinternals.com/files/SysinternalsSuite.zip
        7z x SysinternalsSuite.zip
        choco install notepadplusplus
      shell: bash
    - name: Add registry settings
      run: |
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\AppVeyor\Build Agent\State" /V GetSources /T REG_SZ /D true /F
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v HideFileExt /t REG_DWORD /d 0 /f
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v ShowSuperHidden /t REG_DWORD /d 0 /f
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v Hidden /t REG_DWORD /d 1 /f
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v ShowSecondsInSystemClock /t REG_DWORD /d 1 /f
    - name: Enable Remote Desktop
      run: | 
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Enable-NetFirewallRule -DisplayName "Remote Desktop - User Mode (TCP-in)"
        netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name "UserAuthentication" -Value 1
    - name: Run ssh
      run: |
        ssh -p 443 -R0:127.0.0.1:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 ${{ env.PINGGY_TOKEN }}tcp@ap.free.pinggy.io &
        sleep 5
      shell: bash
    - name: Preview session
      run: |
        call .\files\NGROK-CHECK.bat
      shell: cmd
    - name: Pause Build
      run: |
        $PauseBuild = $true;
        if($PauseBuild){
        $path = "$($env:USERPROFILE)\Desktop\Delete me to continue build.txt"
        # create "lock" file.
        Set-Content -Path $path -Value ''    
        Write-Warning "Build paused. To resume it, open a RDP session, delete 'Delete me to continue build.txt' file on Desktop."
        # wait until "lock" file is deleted by user.
        while(Test-Path $path) {
          Start-Sleep -Seconds 1
        }
        Write-Host "Build lock file has been deleted. Resuming build."}
      shell: powershell
