name: CI
env:
  PINGGY_TOKEN: ${{ secrets.PINGGY_TOKEN }}
  EMAIL: ${{ secrets.EMAIL }}
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: runneradmin
    runs-on: windows-latest
    steps:
    - name: Git check
      run: |
        git --version
    - name: Setup MozillaBuild
      run: |
        aria2c https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe
        start /W MozillaBuildSetup-Latest.exe /S
        cmd /c C:\mozilla-build\start-shell.bat
        erase MozillaBuildSetup-Latest.exe
      shell: cmd
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: amd64
    - name: Download extra software
      run: |
        aria2c https://download.sysinternals.com/files/SysinternalsSuite.zip
        7z x SysinternalsSuite.zip
      shell: bash
    - name: Apply preferred Explorer settings
      run: |
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\AppVeyor\Build Agent\State" /V GetSources /T REG_SZ /D true /F
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v HideFileExt /t REG_DWORD /d 0 /f
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v ShowSuperHidden /t REG_DWORD /d 0 /f
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v Hidden /t REG_DWORD /d 1 /f
        REG ADD HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v ShowSecondsInSystemClock /t REG_DWORD /d 1 /f
        Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize -Name SystemUsesLightTheme -Value 0
        Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize -Name AppsUseLightTheme -Value 0
        Set-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer -Name "ShowRecent" -Value 0
        Set-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer -Name "ShowFrequent" -Value 0
        Set-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer -Name "ShowCloudFiles" -Value 0
        Set-ItemProperty -Path "HKCU:\Control Panel\Desktop" -Name WallPaper -Value ""
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Wallpapers" -Name BackgroundType -Value 1
        Set-ItemProperty -Path "HKCU:\Control Panel\Colors" -Name Background -Value "0 0 0"
        Stop-Process -Name explorer -Force; Start-Process explorer.exe
    - name: Enable Remote Desktop
      run: | 
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Enable-NetFirewallRule -DisplayName "Remote Desktop - User Mode (TCP-in)"
        netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name "UserAuthentication" -Value 1
    - name: Display remote desktop connection for debug
      run: |
        FULL_SHA="${{ github.sha }}"
        SHORT_SHA="${FULL_SHA:0:7}"
        P2X="${SHORT_SHA}A1!"
        net user runneradmin "$P2X"
        echo "=========================================="
        ssh -p 443 -L4300:localhost:4300 -R0:127.0.0.1:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 tcp@ap.free.pinggy.io &
        sleep 10
        echo "=========================================="
        echo "USER: runneradmin"
        echo "PASS: $P2X"
        echo "=========================================="
      shell: bash
    - name: Add mercurial to PATH
      run: |
        python -m pip uninstall mercurial -y || true
        python -m pip install mercurial --no-cache-dir --force-reinstall
        echo "$env:USERPROFILE\AppData\Roaming\Python\Python311\Scripts" >> $env:GITHUB_PATH
      shell: pwsh
    - name: Pause Build
      if: github.event.inputs.debug != 'false'
      run: |
        $PauseBuild = $true;
        if($PauseBuild){
        $path = "$($env:USERPROFILE)\Desktop\Delete me to continue build.txt"
        # create "lock" file.
        Set-Content -Path $path -Value ''    
        Write-Warning "Build paused. To resume it, open a RDP session, delete 'Delete me to continue build.txt' file on Desktop."
        # wait until "lock" file is deleted by user.
        while(Test-Path $path) {
          Start-Sleep -Seconds 1
        }
        Write-Host "Build lock file has been deleted. Resuming build."}
      shell: powershell
