name: Build on Ubuntu
env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  CARGO_TERM_COLOR: always
  MOZBOOT_NO_CLONE: 1

on:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Update components
      shell: bash
      run: |
        sudo timedatectl set-timezone Asia/Manila
        sudo sed -i 's|http://azure.|http://|g' /etc/apt/apt-mirrors.txt
        sudo sed -i 's|http://azure.|http://|g' /etc/apt/sources.list
        sudo chmod 0644 /boot/vmlinuz*
        sudo chmod +r /boot/vmlinuz-*
        sudo add-apt-repository universe
        sudo apt-get update && sudo sudo apt-get upgrade && sudo apt install p7zip-full curl python3 python3-full python3-pip mercurial python3-venv git nsis zip unzip msitools
        source /etc/os-release

    - name: Install Mercurial
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade mercurial
        python3 -m pip install mercurial --no-cache-dir --force-reinstall
        echo 'export PATH="'"$(python3 -m site --user-base)"'/bin:$PATH"' >> $GITHUB_PATH
        hg version

    - name: Clone repository
      shell: bash
      run: |
        hg clone --stream https://hg.mozilla.org/mozilla-unified ../mozilla-unified
        ls -alh
        cd ../mozilla-unified
        ls -alh

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.6
      with:
        version: "v0.7.1"
        
    - name: Build
      continue-on-error: true
      env:
        SCCACHE_GHA_ENABLED: "true"
        RUSTC_WRAPPER: "sccache"
        SCCACHE_IDLE_TIMEOUT: "0" 
      shell: bash
      run: |
        cd ../mozilla-unified
        hg pull && hg update
        ./mach bootstrap --application-choice=browser
        echo "mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-x86_64-pc-mingw32" > .mozconfig
        echo "ac_add_options --with-ccache=sccache" >> .mozconfig
        echo "ac_add_options --target=x86_64-pc-mingw32" >> ./.mozconfig
        echo "ac_add_options --with-branding=browser/branding/official" >> .mozconfig
        echo "ac_add_options --enable-release" >> .mozconfig
        echo "ac_add_options --enable-optimize" >> .mozconfig
        echo "ac_add_options --disable-debug-symbols" >> .mozconfig
        echo "ac_add_options --disable-tests" >> .mozconfig
        echo "ac_add_options --disable-debug" >> .mozconfig
        echo "ac_add_options --disable-updater" >> .mozconfig
        echo "ac_add_options --disable-crashreporter" >> .mozconfig
        export MOZCONFIG=.mozconfig
        ./mach bootstrap --application-choice=browser
        ./mach clobber
        ./mach build
        ./mach package

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: |
          **/obj-x86_64-pc-mingw32/dist/*.installer.exe
        
#    - name: Bootstrap a copy of the Firefox source code
#      run: |
#        cd ..
#        rm -rf mozilla-unified
#        curl https://hg-edge.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py -O
#        python3 bootstrap.py --no-interactive --application-choice browser
#        mv firefox mozilla-unified
#        ls -alh

    - name: Commit
      run: |
        git init
        git reset --hard HEAD
        7z a -tzip "tmp.zip" -r "../../${{ github.event.repository.name }}" -x!*.git -mx0
        7z x "tmp.zip" -O"../"
        rm -f tmp.zip
        cd ${{ github.event.repository.name }}
        ls -alh
        rm -rf .git
        cd ../mozilla-unified
        git init -b release
        git init && git symbolic-ref HEAD refs/heads/release
        git remote add origin https://${{ env.GITHUB_TOKEN }}@github.com/test6744/firefox.git
        git remote add upstream https://github.com/mozilla-firefox/firefox.git
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git config push.showProgress false
        git config --global core.autocrlf input
        git add . > /dev/null 2>&1
        git commit -m "Starting point; Initial commit" --quiet
        git push -f https://${{ env.GITHUB_TOKEN }}@github.com/test6744/firefox.git --quiet
      shell: bash
