name: Build on Windows
env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  SCCACHE_DIR: 'C:/Users/runneradmin/AppData/Local/Mozilla/sccache'
  SCCACHE_IDLE_TIMEOUT: "0" 
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'DEBUG mode - TRUE enables RDP SESSION'
        default: false
        required: true
        type: choice
        options:
        - true
        - false
      build_mode:
        description: 'BUILD mode'
        default: 'Full'
        required: true
        type: choice
        options:
        - Artifact
        - Full
      variant:
        description: 'Release Type'
        default: 'Stable Release (Official)'
        required: true
        type: choice
        options:
        - Enterprise Release (Official)
        - Stable Release (Official)
        - Stable Release (Deprecated)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}
      short_sha: ${{ steps.var.outputs.short_sha }}
    steps:
    - name: Checkout (${{ inputs.variant }})
      uses: actions/checkout@v4
      with:
        repository: >-
          ${{ 
            inputs.variant == 'Enterprise Release (Official)' && 'mozilla/enterprise-firefox' ||
            inputs.variant == 'Stable Release (Official)'     && 'mozilla-firefox/firefox' ||
            inputs.variant == 'Stable Release (Deprecated)'     && 'mozilla/gecko-dev'
          }}
        persist-credentials: false
        fetch-depth: 1

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9
          
    - name: Cache build state
      uses: actions/cache@v5
      with:
        path: |
          ~/.mozbuild
          ~/.rustup
          ~/.cargo
          D:\mozbuild
        key: |
          ${{ runner.os }}-mozilla-build-${{ hashFiles('**/mozconfig', '**/bootstrap.py') }}
        restore-keys: |
          ${{ runner.os }}-mozilla-build-

    - name: Cache Sccache
      uses: actions/cache@v5
      with:
        path: |
          ${{ env.SCCACHE_DIR }}
        key: |
          ${{ runner.os }}-sccache-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-sccache-

    - name: Link checkout
      run: |
        cd ../../../..
        mkdir mozilla-source
        mklink /J "D:\mozilla-source\mozilla-unified" "D:\a\runner-vm\runner-vm"
        mklink /J "D:\mozilla-source\firefox" "D:\a\runner-vm\runner-vm"
      shell: cmd

    - name: Setup MozillaBuild
      run: |
        aria2c https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe
        start /W MozillaBuildSetup-Latest.exe /S
        cmd /c C:\mozilla-build\start-shell.bat
        erase MozillaBuildSetup-Latest.exe
      shell: cmd

    - name: Enable remote desktop for debug
      if: github.event.inputs.debug != false
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Enable-NetFirewallRule -DisplayName 'Remote Desktop - User Mode (TCP-in)'
        netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      
    - name: Add mercurial to PATH
      run: |
        /c/mozilla-build/python3/python3.exe -m pip uninstall mercurial -y
        /c/mozilla-build/python3/python3.exe -m pip install mercurial --no-cache-dir --force-reinstall
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Test mach command
      if: github.event.inputs.debug != false
      run: |
        cd /d/mozilla-source/mozilla-unified
        ls -alh
        hg version
        ./mach settings
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Checkout preferred patch
      if: github.event.inputs.build_mode == 'Full'
      run: |
        git clone https://github.com/${{ github.repository }}.git custom-patch
        7z x custom-patch/patch.zip -o../runner-vm
        rm -rf custom-patch
      shell: bash

    - name: Display remote desktop connection for debug (Phase I)
      if: github.event.inputs.debug != false
      run: |
        FULL_SHA="${{ github.sha }}"
        SHORT_SHA="${FULL_SHA:0:7}"
        P2X="${SHORT_SHA}A1!"
        net user runneradmin "$P2X"
        echo "=========================================="
        ssh -p 443 -L4300:localhost:4300 -R0:127.0.0.1:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 tcp@ap.free.pinggy.io &
        sleep 10
        echo "=========================================="
        echo "USER: runneradmin"
        echo "PASS: $P2X"
        echo "=========================================="
      shell: bash

    - name: Pause Build (Phase I)
      if: github.event.inputs.debug != false
      run: |
        $PauseBuild = $true;
        if($PauseBuild){
        $path = "$($env:USERPROFILE)\Desktop\Delete me to continue build.txt"
        # create "lock" file.
        Set-Content -Path $path -Value ''    
        Write-Warning "Build paused. To resume it, open a RDP session, delete 'Delete me to continue build.txt' file on Desktop."
        # wait until "lock" file is deleted by user.
        while(Test-Path $path) {
          Start-Sleep -Seconds 1
        }
        Write-Host "Build lock file has been deleted. Resuming build."}
      shell: powershell

    - name: Apply patch
      if: github.event.inputs.debug != false
      run: |
        git apply installer.nsi.patch
        git apply test.patch
      shell: bash

    - name: Define build config
      if: github.event.inputs.build_mode == 'Full'
      run: |
        cat <<EOF > /d/mozilla-source/mozilla-unified/.mozconfig
        ac_add_options --target=x86_64-pc-windows-msvc
        ac_add_options --with-ccache=sccache
        ac_add_options --with-branding=browser/branding/enterprise
        ac_add_options --enable-release
        ac_add_options --enable-optimize
        ac_add_options --disable-debug-symbols
        ac_add_options --disable-tests
        ac_add_options --disable-debug
        mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-x86_64-pc-windows-msvc
        EOF
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Define build config
      if: github.event.inputs.build_mode == 'Artifact'
      run: |
        cat <<EOF > /d/mozilla-source/mozilla-unified/.mozconfig
        ac_add_options --target=x86_64-pc-windows-msvc
        mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-x86_64-pc-windows-msvc
        EOF
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'
      
    - name: Build
      if: github.event.inputs.build_mode == 'Full'
      run: |
        sccache --start-server
        rustup update stable
        export MOZBUILD_STATE_PATH="/d/mozbuild"
        export MOZ_APP_NAME=firefox-enterprise
        cd /d/mozilla-source/mozilla-unified
        ./mach clobber
        ./mach build
        ./mach package
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Build
      if: github.event.inputs.build_mode == 'Artifact'
      run: |
        sccache --start-server
        rustup update stable
        export MOZBUILD_STATE_PATH="/d/mozbuild"
        cd /d/mozilla-source/mozilla-unified
        ./mach clobber
        ./mach build
        ./mach package
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Display remote desktop connection for debug (Phase II)
      if: github.event.inputs.debug != false
      run: |
        taskkill //F //IM ssh.exe //T || true
        FULL_SHA="${{ github.sha }}"
        SHORT_SHA="${FULL_SHA:0:7}"
        P2X="${SHORT_SHA}A1!"
        net user runneradmin "$P2X"
        echo "=========================================="
        ssh -p 443 -L4300:localhost:4300 -R0:127.0.0.1:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 tcp@ap.free.pinggy.io &
        sleep 10
        echo "=========================================="
        echo "USER: runneradmin"
        echo "PASS: $P2X"
        echo "=========================================="
      shell: bash

    - name: Pause Build (Phase II)
      if: github.event.inputs.debug != false
      run: |
        $PauseBuild = $true;
        if($PauseBuild){
        $path = "$($env:USERPROFILE)\Desktop\Delete me to continue build.txt"
        # create "lock" file.
        Set-Content -Path $path -Value ''    
        Write-Warning "Build paused. To resume it, open a RDP session, delete 'Delete me to continue build.txt' file on Desktop."
        # wait until "lock" file is deleted by user.
        while(Test-Path $path) {
          Start-Sleep -Seconds 1
        }
        Write-Host "Build lock file has been deleted. Resuming build."}
      shell: powershell
      
    - name: List files
      run: |
        cd /d/mozilla-source/mozilla-unified
        ls -alh
        sccache --show-stats
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6
      with:
        name: installer
        path: |
          obj-x86_64-pc-windows-msvc/dist/*.installer.exe

    - id: var
      name: Generate Build Info
      run: |
        git init
        echo "full_sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
        echo "short_sha=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    needs: build
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
      var_build_num: ${{ steps.var_build_num.outputs.var_build_num }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: mozilla/enterprise-firefox
        persist-credentials: false
        ref: ${{ github.head_ref }}
        fetch-depth: 1

    - id: should_run
      continue-on-error: true
      name: Check if latest commit date is within the previous 24 hours
      run: |
        test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "should_run=false" >> $GITHUB_OUTPUT

    - id: var_build_num
      continue-on-error: true
      name: Read Build Number
      run: |
        echo "var_build_num=$(cat browser/config/version_display.txt)" >> $GITHUB_OUTPUT
        cat browser/config/version_display.txt

  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: [ build, check_date ]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          name: installer
      
      - name: Echo build sha256
        id: build_sha
        run: |
          INSTALLER_FILE=$(ls *.installer.exe)
          mkdir -p ./extracted_content
          7z x "$INSTALLER_FILE" -o./extracted_content/
          cd ./extracted_content
          find . -type f -exec sha256sum {} + > ../filelist.sha256
          cd ..
          sha256sum "$INSTALLER_FILE" > "$INSTALLER_FILE.sha256"
          HASH_ONLY=$(sha256sum "$INSTALLER_FILE" | cut -d ' ' -f 1)
          cat filelist.sha256
          echo "Main Installer Hash:"
          echo "build_sha=$HASH_ONLY" >> $GITHUB_OUTPUT
          echo "File count: $(wc -l < filelist.sha256)"

      - name: Upload Firefox to GitHub Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: Nightly v${{ needs.check_date.outputs.var_build_num }}-${{ github.run_number }} [${{ needs.build.outputs.short_sha }}]
          tag_name: nightly
          body: |
            **This release has been built by [Github Actions]**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            Build SHA256:
            ```
            ${{ steps.build_sha.outputs.build_sha }}
            ```
            To verify the build SHA256 during the action, click the build link, go-to "Create Release", open the Echo build sha256 step and read the sha256.

            These are nightly/experimental builds of Mozilla Firefox (Enterprise Edition) and may be unstable; Use at your OWN risk :warning:.

            Full Commit Hash:
            ```
            ${{ needs.build.outputs.full_sha }}
            ```
          files: |
            firefox-*-*.*.*.*.installer.exe
            *.sha256
          token: ${{ env.GH_TOKEN }}
