name: Build on Windows
env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  SCCACHE_DIR: 'D:/.cache/sccache'
  SCCACHE_IDLE_TIMEOUT: "0" 
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
  MOZBUILD_STATE_PATH: 'D:/mozbuild'
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'DEBUG mode - TRUE enables RDP SESSION'
        default: 'false'
        required: true
        type: choice
        options:
        - true
        - false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022
    name: Build
    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}
      short_sha: ${{ steps.var.outputs.short_sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: test6744/mozilla-unified
        persist-credentials: false
        ref: ${{ github.head_ref }}
        fetch-depth: 1

    - name: Run sccache
      uses: mozilla-actions/sccache-action@v0.0.9
          
    - name: Cache sccache
      uses: actions/cache@v5
      with:
        path: |
          ${{ env.SCCACHE_DIR }}
        key: |
          ${{ runner.os }}-sccache-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-sccache-

    - name: Link checkout
      run: |
        cd ../../../..
        mkdir mozilla-source
        mklink /J "D:\mozilla-source\mozilla-unified" "D:\a\runner-vm\runner-vm"
        mklink /J "D:\mozilla-source\firefox" "D:\a\runner-vm\runner-vm"
      shell: cmd

    - name: Setup MozillaBuild
      if: github.event.inputs.debug != 'false'
      run: |
        aria2c https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe
        start /W MozillaBuildSetup-Latest.exe /S
        cmd /c C:\mozilla-build\start-shell.bat
        erase MozillaBuildSetup-Latest.exe
      shell: cmd

    - name: Enable remote desktop for debug
      if: github.event.inputs.debug != 'false'
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Enable-NetFirewallRule -DisplayName 'Remote Desktop - User Mode (TCP-in)'
        netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      
    - name: Add mercurial to PATH
      if: github.event.inputs.debug != 'false'
      run: |
        /c/mozilla-build/python3/python3.exe -m pip uninstall mercurial -y
        /c/mozilla-build/python3/python3.exe -m pip install mercurial --no-cache-dir --force-reinstall
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Test mach command
      if: github.event.inputs.debug != 'false'
      run: |
        cd /d/mozilla-source/mozilla-unified
        ls -alh
        hg version
        ./mach settings
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Checkout preferred patch
      run: |
        git clone https://github.com/${{ github.repository }}.git custom-patch
        7z x custom-patch/patch.zip -o../runner-vm
        rm -rf custom-patch
      shell: bash

    - name: Display remote desktop connection for debug
      if: github.event.inputs.debug != 'false'
      run: |
        FULL_SHA="${{ github.sha }}"
        SHORT_SHA="${FULL_SHA:0:7}"
        P2X="${SHORT_SHA}A1!"
        net user runneradmin "$P2X"
        echo "=========================================="
        ssh -p 443 -L4300:localhost:4300 -R0:127.0.0.1:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 tcp@ap.free.pinggy.io &
        sleep 10
        echo "=========================================="
        echo "USER: runneradmin"
        echo "PASS: $P2X"
        echo "=========================================="
      shell: bash

    - name: Pause Build
      if: github.event.inputs.debug != 'false'
      run: |
        $PauseBuild = $true;
        if($PauseBuild){
        $path = "$($env:USERPROFILE)\Desktop\Delete me to continue build.txt"
        # create "lock" file.
        Set-Content -Path $path -Value ''    
        Write-Warning "Build paused. To resume it, open a RDP session, delete 'Delete me to continue build.txt' file on Desktop."
        # wait until "lock" file is deleted by user.
        while(Test-Path $path) {
          Start-Sleep -Seconds 1
        }
        Write-Host "Build lock file has been deleted. Resuming build."}
      shell: powershell

    - name: Apply patch
      if: github.event.inputs.debug != 'false'
      run: |
        git apply installer.nsi.patch
        git apply nsToolkitProfileService.cpp.patch
      shell: bash

    - name: Setup sccache
      run: |
        cargo install sccache --locked
        ./mach bootstrap --no-interactive --application-choice=browser
      shell: bash

    - name: Configure .mozconfig
      run: |
        echo 'mk_add_options MOZ_OBJDIR=D:/objdir' >> .mozconfig
        echo 'ac_add_options --enable-release' >> .mozconfig
        echo 'ac_add_options --with-ccache=sccache' >> .mozconfig
        echo 'ac_add_options --disable-tests' >> .mozconfig
        echo 'ac_add_options --disable-debug' >> .mozconfig
        echo 'ac_add_options --disable-crashreporter' >> .mozconfig
        echo 'ac_add_options --disable-updater' >> .mozconfig
      
    - name: Build
      run: |
        cd /d/mozilla-source/mozilla-unified
        ./mach build -j%NUMBER_OF_PROCESSORS%
        ./mach package

    - name: Display remote desktop connection for debug
      if: github.event.inputs.debug != 'false'
      run: |
        FULL_SHA="${{ github.sha }}"
        SHORT_SHA="${FULL_SHA:0:7}"
        P2X="${SHORT_SHA}A1!"
        net user runneradmin "$P2X"
        echo "=========================================="
        ssh -p 443 -L4300:localhost:4300 -R0:127.0.0.1:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 tcp@ap.free.pinggy.io &
        sleep 10
        echo "=========================================="
        echo "USER: runneradmin"
        echo "PASS: $P2X"
        echo "=========================================="
      shell: bash

    - name: Pause Build
      if: github.event.inputs.debug != 'false'
      run: |
        $PauseBuild = $true;
        if($PauseBuild){
        $path = "$($env:USERPROFILE)\Desktop\Delete me to continue build.txt"
        # create "lock" file.
        Set-Content -Path $path -Value ''    
        Write-Warning "Build paused. To resume it, open a RDP session, delete 'Delete me to continue build.txt' file on Desktop."
        # wait until "lock" file is deleted by user.
        while(Test-Path $path) {
          Start-Sleep -Seconds 1
        }
        Write-Host "Build lock file has been deleted. Resuming build."}
      shell: powershell
      
    - name: List files
      run: |
        cd /d/mozilla-source/mozilla-unified
        ls -alh
        sccache --show-stats
      shell: bash

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6
      with:
        name: installer
        path: |
          objdir/dist/install/sea/*.exe

    - id: var
      name: Generate Build Info
      run: |
        git init
        echo "full_sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
        echo "short_sha=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    needs: build
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
      var_build_num: ${{ steps.var_build_num.outputs.var_build_num }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: test6744/mozilla-unified
        persist-credentials: false
        ref: ${{ github.head_ref }}
        fetch-depth: 1

    - id: should_run
      continue-on-error: true
      name: Check if latest commit date is within the previous 24 hours
      run: |
        test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "should_run=false" >> $GITHUB_OUTPUT

    - id: var_build_num
      continue-on-error: true
      name: Read Build Number
      run: |
        echo "var_build_num=$(cat browser/config/version_display.txt)" >> $GITHUB_OUTPUT
        cat browser/config/version_display.txt

  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: [ build, check_date ]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          name: installer
      
      - name: Echo build sha256
        id: build_sha
        run: |
          INSTALLER_FILE=$(ls *.installer.exe)
          mkdir -p ./tmp
          7z x "$INSTALLER_FILE" -o./tmp/
          cd ./tmp
          find . -type f -exec sha256sum {} + > ../filelist.sha256
          cd ..
          sha256sum "$INSTALLER_FILE" > "$INSTALLER_FILE.sha256" >> $GITHUB_OUTPUT
          HASH_ONLY=$(sha256sum "$INSTALLER_FILE" | cut -d ' ' -f 1)
          cat filelist.sha256
          echo "Main Installer Hash:"
          echo "build_sha=$HASH_ONLY" >> $GITHUB_OUTPUT
          echo "File count: $(wc -l < filelist.sha256)"

      - name: Upload Firefox to GitHub Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: Release Nightly v${{ needs.check_date.outputs.var_build_num }}-${{ github.run_number }} [${{ needs.build.outputs.short_sha }}]
          repository: test6744/mozilla-unified
          tag_name: release
          token: ${{ env.GH_TOKEN }}
          body: |
            **This release has been built by [Github Actions]**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            Build SHA256:
            ```
            ${{ steps.build_sha.outputs.build_sha }}
            ```
            To verify the build SHA256 during the action, click the build link, go-to "Create Release", open the Echo build sha256 step and read the sha256.

            These are nightly/experimental builds of Mozilla Firefox and may be unstable; Use at your OWN risk :warning:.

            Full Commit Hash:
            ```
            ${{ needs.build.outputs.full_sha }}
            ```
          files: |
            *.installer.exe
            *.sha256

