name: Build firefox on Windows
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_firefox:
    env:
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    runs-on: windows-2019
    steps:
    - name: Checkout Phase I
      uses: actions/checkout@v4
      with:
        repository: mozilla-firefox/firefox
        persist-credentials: false
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Checkout Phase II
      run: |
        git init && git symbolic-ref HEAD refs/heads/release
        git remote add origin https://github.com/mozilla-firefox/firefox.git
        git pull
        
    - name: Cache
      uses: actions/cache@v5
      with:
        path: |
          ~/.mozbuild
          ~/.rustup
          ~/.cargo
          C:\mozilla-source\mozilla-unified\.git
        key: ${{ runner.os }}-firefox-${{ hashFiles('**/mozconfig', '**/bootstrap.py') }}
        restore-keys: |
            ${{ runner.os }}-mozbuild

    - name: Link checkout
      run: |
        cd ../../../..
        mkdir mozilla-source
        mklink /J "D:\mozilla-source\mozilla-unified" "D:\a\runner-vm\runner-vm"
        mklink /J "D:\mozilla-source\firefox" "D:\a\runner-vm\runner-vm"
      shell: cmd

    - name: Setup MozillaBuild
      run: |
        choco install mozillabuild -y --no-progress --limit-output
        cmd /c C:\mozilla-build\start-shell.bat
      shell: cmd

    - name: Enable remote desktop for debug
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Enable-NetFirewallRule -DisplayName 'Remote Desktop - User Mode (TCP-in)'
        netsh advfirewall firewall set rule group="Remote Desktop" new enable=yes
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Display remote desktop connection
      run: |
        FULL_SHA="${{ github.sha }}"
        SHORT_SHA="${FULL_SHA:0:7}"
        P2X="${SHORT_SHA}A1!"
        net user runneradmin "$P2X"
        ssh -p 443 -R0:127.0.0.1:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 tcp@ap.free.pinggy.io &
        echo "=========================================="
        echo "USER: runneradmin"
        echo "PASS: $P2X"
        echo "=========================================="
      shell: bash
      
    - name: Add mercurial to PATH
      run: |
        /c/mozilla-build/python3/python3.exe -m pip uninstall mercurial -y
        /c/mozilla-build/python3/python3.exe -m pip install mercurial --no-cache-dir --force-reinstall
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Start bootstrapper
      run: |
        cd /d/mozilla-source/mozilla-unified
        ls -alh
        hg version
        ./mach settings
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'

    - name: Define build config
      run: |
        cd /d/mozilla-source/mozilla-unified
        cat <<EOF > .mozconfig
        ac_add_options --target=x86_64-pc-mingw32
        ac_add_options --enable-release
        ac_add_options --enable-optimize
        ac_add_options --disable-debug-symbols
        mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-firefox-windows
        EOF
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'
      
    - name: Build
      run: |
        PYTHON_SCRIPTS_PATH=$(/c/mozilla-build/python3/python3.exe -c "import sysconfig; print(sysconfig.get_path('scripts'))")
        export PATH="$PYTHON_SCRIPTS_PATH:$PATH"
        cd /d/mozilla-source/mozilla-unified
        ./mach clobber
        ./mach build
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'
      
    - name: List files
      run: |
        cd /d/mozilla-source/mozilla-unified
        ls -alh
      shell: 'C:\mozilla-build\msys2\usr\bin\bash.exe --noprofile --norc -e -o pipefail {0}'
